# Generated by Django 5.0.3 on 2024-03-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower_profile',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following_profile',
        ),
    ]
