# Generated by Django 5.0.3 on 2024-03-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('❤️', 'Love')], max_length=100),
        ),
    ]
