# Generated by Django 5.0.2 on 2024-03-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reaction_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='post_id',
        ),
    ]
