# Generated by Django 5.0.2 on 2024-03-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('😄', 'Happy'), ('😢', 'Sad'), ('❤️', 'Love'), ('👎', 'Dislike'), ('😐', 'Normal')], max_length=100),
        ),
    ]
