# Generated by Django 5.0.2 on 2024-03-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reaction_post_alter_reaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('😄', 'Happy'), ('😢', 'Sad'), ('❤️', 'Love'), ('👎', 'Dislike'), ('👍', 'Like')], max_length=100),
        ),
    ]
