# Generated by Django 5.0.3 on 2024-03-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='gender',
        ),
    ]
